[package]
name = "zakura-halo2-gadgets"
description = "Reusable gadgets and chip implementations for Halo 2"
keywords = ["cryptography", "halo2", "zero-knowledge", "zkp", "zcash"]
categories = ["cryptography"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[lib]
name = "halo2_gadgets"
bench = false

[dependencies]
arrayvec = "0.7.0"
ff = "0.14"
group = "0.14"
halo2_poseidon = { workspace = true }
halo2_proofs = { workspace = true }
maybe-rayon = { version = "0.1.0", default-features = false, optional = true }
pasta_curves = { workspace = true, features = ["default"] }
plotters = { version = "0.3.0", optional = true, default-features = false }
proptest = { version = "1.0.0", optional = true }
sinsemilla = { workspace = true }
subtle = "2.3"

[dev-dependencies]
criterion = "0.3"
halo2_poseidon = { workspace = true, features = ["test-dependencies"] }
proptest = "1.0.0"
rand = "0.10"
sinsemilla = { workspace = true, features = ["test-dependencies"] }

[target."cfg(unix)".dev-dependencies]
inferno = ">=0.11, <0.11.5"
pprof = { version = "0.8", features = ["criterion", "flamegraph"] }

[features]
beta = ["halo2_proofs/beta"]
multicore = ["dep:maybe-rayon", "halo2_proofs/multicore", "maybe-rayon/threads"]
nightly = ["beta", "halo2_proofs/nightly", "unstable-sha256-gadget"]
test-dependencies = ["proptest", "sinsemilla/test-dependencies"]
test-dev-graph = [
    "halo2_proofs/dev-graph",
    "plotters",
    "plotters/bitmap_backend",
    "plotters/bitmap_encoder",
    "plotters/ttf",
]
unstable-sha256-gadget = []

[[bench]]
name = "poseidon"
harness = false

[[bench]]
name = "primitives"
harness = false

[[bench]]
name = "sha256"
harness = false
required-features = ["unstable-sha256-gadget"]
