[package]
name = "zakura-reddsa-frost"
description = "FROST threshold signatures for RedJubjub and RedPallas"
keywords = ["cryptography", "signatures", "frost", "zcash"]
categories = ["cryptography", "no-std"]
version = "1.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "reddsa_frost"

[dependencies]
blake2b_simd = { version = "1", default-features = false }
frost-rerandomized = { version = "3.0.0", features = ["serialization"], default-features = false }
group = { version = "0.14", default-features = false }
jubjub = { workspace = true }
pasta_curves = { workspace = true }
rand_core = { version = "0.10", default-features = false }
rand_core_06 = { version = "0.6", features = ["getrandom"], default-features = false, package = "rand_core" }
reddsa = { workspace = true, features = ["alloc"] }

[dev-dependencies]
criterion = "0.6"
frost-rerandomized = { version = "3.0.0", features = ["test-impl"] }
hex = "0.4.3"
rand_core_06 = { version = "0.6", features = ["getrandom"], package = "rand_core" }

[features]
default = ["std"]
serde = ["frost-rerandomized/serde"]
std = ["blake2b_simd/std", "reddsa/std", "serde"]

[[bench]]
name = "frost"
harness = false
