use std::{fmt::Write, path::PathBuf};

use ff::PrimeField;
use halo2_gadgets::ecc::chip::{constants::compute_lagrange_coeffs, FixedPoint, FixedScalarKind};
use orchard::constants::{
    fixed_bases::{NUM_WINDOWS, NUM_WINDOWS_SHORT},
    OrchardBaseFieldBases, OrchardFixedBasesFull, OrchardShortScalarBases,
};
use pasta_curves::pallas;

/// Emits one table. The window count comes from the base's
/// `FixedScalarKind`, exactly as the `FixedPoint::lagrange_coeffs` default
/// derives it, so the generated table cannot disagree with the trait.
fn emit<B: FixedPoint<pallas::Affine>>(output: &mut String, name: &str, base: B) {
    let windows = <B::FixedScalarKind as FixedScalarKind>::NUM_WINDOWS;
    let length = match windows {
        NUM_WINDOWS => "NUM_WINDOWS",
        NUM_WINDOWS_SHORT => "NUM_WINDOWS_SHORT",
        other => panic!("no named constant for {other} windows"),
    };
    writeln!(
        output,
        "#[rustfmt::skip]\npub(super) static {name}: [[pallas::Base; H]; {length}] = ["
    )
    .unwrap();
    for window in compute_lagrange_coeffs(base.generator(), windows) {
        writeln!(output, "    [").unwrap();
        for coefficient in window {
            let repr = coefficient.to_repr();
            let limbs: Vec<u64> = repr
                .as_ref()
                .as_chunks::<8>()
                .0
                .iter()
                .map(|limb| u64::from_le_bytes(*limb))
                .collect();
            writeln!(
                output,
                "        pallas::Base::from_raw([0x{:016x}, 0x{:016x}, 0x{:016x}, 0x{:016x}]),",
                limbs[0], limbs[1], limbs[2], limbs[3],
            )
            .unwrap();
        }
        writeln!(output, "    ],").unwrap();
    }
    writeln!(output, "];\n").unwrap();
}

fn main() {
    let path = PathBuf::from(std::env::args_os().nth(1).expect("output path"));
    let mut output = String::from(
        "// This file is generated by `generate_lagrange_coeffs`. Do not edit it by\n\
         // hand. To regenerate it (the `unstable-voting-circuits` feature exposes\n\
         // the `constants` module to the example):\n\
         //\n\
         //     cargo run --release -p zakura-orchard \\\n\
         //         --example generate_lagrange_coeffs \\\n\
         //         --features circuit,unstable-voting-circuits \\\n\
         //         -- orchard/src/constants/fixed_bases/lagrange_coeffs.rs\n\
         //     rustfmt --edition 2021 orchard/src/constants/fixed_bases/lagrange_coeffs.rs\n\
         //\n\
         // `precomputed_lagrange_coeffs_match_generators` in `fixed_bases.rs`\n\
         // checks the committed tables against fresh interpolation.\n\n\
         use pasta_curves::pallas;\n\n\
         use super::{H, NUM_WINDOWS, NUM_WINDOWS_SHORT};\n\n",
    );

    emit(
        &mut output,
        "COMMIT_IVK_R",
        OrchardFixedBasesFull::CommitIvkR,
    );
    emit(
        &mut output,
        "NOTE_COMMIT_R",
        OrchardFixedBasesFull::NoteCommitR,
    );
    emit(
        &mut output,
        "VALUE_COMMIT_R",
        OrchardFixedBasesFull::ValueCommitR,
    );
    emit(
        &mut output,
        "SPEND_AUTH_G",
        OrchardFixedBasesFull::SpendAuthG,
    );
    emit(
        &mut output,
        "NULLIFIER_K",
        OrchardBaseFieldBases::NullifierK,
    );
    emit(
        &mut output,
        "VALUE_COMMIT_V",
        OrchardShortScalarBases::ValueCommitV,
    );
    emit(
        &mut output,
        "SPEND_AUTH_G_SHORT",
        OrchardShortScalarBases::SpendAuthGShort,
    );

    output.pop();
    std::fs::write(path, output).unwrap();
}
