use std::{fmt::Write, path::PathBuf};

use ff::PrimeField;
use halo2_gadgets::ecc::chip::{constants::compute_lagrange_coeffs, FixedPoint};
use orchard::constants::{
    fixed_bases::{NUM_WINDOWS, NUM_WINDOWS_SHORT},
    OrchardBaseFieldBases, OrchardFixedBasesFull, OrchardShortScalarBases,
};
use pasta_curves::pallas;

fn emit<B: FixedPoint<pallas::Affine>>(
    output: &mut String,
    name: &str,
    base: B,
    windows: usize,
    length: &str,
) {
    writeln!(
        output,
        "#[rustfmt::skip]\npub(super) const {name}: [[pallas::Base; H]; {length}] = ["
    )
    .unwrap();
    for window in compute_lagrange_coeffs(base.generator(), windows) {
        writeln!(output, "    [").unwrap();
        for coefficient in window {
            let repr = coefficient.to_repr();
            let limbs: Vec<_> = repr
                .as_ref()
                .chunks_exact(8)
                .map(|limb| u64::from_le_bytes(limb.try_into().unwrap()))
                .collect();
            writeln!(
                output,
                "        pallas::Base::from_raw([0x{:016x}, 0x{:016x}, 0x{:016x}, 0x{:016x}]),",
                limbs[0], limbs[1], limbs[2], limbs[3],
            )
            .unwrap();
        }
        writeln!(output, "    ],").unwrap();
    }
    writeln!(output, "];\n").unwrap();
}

fn main() {
    let path = PathBuf::from(std::env::args_os().nth(1).expect("output path"));
    let mut output = String::from(
        "// This file is generated by `generate_lagrange_coeffs`.\n\
         // Do not edit it by hand.\n\n\
         use pasta_curves::pallas;\n\n\
         use super::{H, NUM_WINDOWS, NUM_WINDOWS_SHORT};\n\n",
    );

    emit(
        &mut output,
        "COMMIT_IVK_R",
        OrchardFixedBasesFull::CommitIvkR,
        NUM_WINDOWS,
        "NUM_WINDOWS",
    );
    emit(
        &mut output,
        "NOTE_COMMIT_R",
        OrchardFixedBasesFull::NoteCommitR,
        NUM_WINDOWS,
        "NUM_WINDOWS",
    );
    emit(
        &mut output,
        "VALUE_COMMIT_R",
        OrchardFixedBasesFull::ValueCommitR,
        NUM_WINDOWS,
        "NUM_WINDOWS",
    );
    emit(
        &mut output,
        "SPEND_AUTH_G",
        OrchardFixedBasesFull::SpendAuthG,
        NUM_WINDOWS,
        "NUM_WINDOWS",
    );
    emit(
        &mut output,
        "NULLIFIER_K",
        OrchardBaseFieldBases::NullifierK,
        NUM_WINDOWS,
        "NUM_WINDOWS",
    );
    emit(
        &mut output,
        "VALUE_COMMIT_V",
        OrchardShortScalarBases::ValueCommitV,
        NUM_WINDOWS_SHORT,
        "NUM_WINDOWS_SHORT",
    );
    emit(
        &mut output,
        "SPEND_AUTH_G_SHORT",
        OrchardShortScalarBases::SpendAuthGShort,
        NUM_WINDOWS_SHORT,
        "NUM_WINDOWS_SHORT",
    );

    output.pop();
    std::fs::write(path, output).unwrap();
}
