[package]
name = "zakura-equihash"
description = "The Equihash Proof-of-Work function"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
std = ["dep:document-features"]

## Experimental Tromp solver support, builds the C solver and Rust FFI layer.
solver = ["dep:cc", "std"]

[dependencies]
corez = { version = "0.1.1", default-features = false, features = ["alloc"] }
blake2b_simd = { version = "1", default-features = false }

# Dependencies used internally:
# (Breaking upgrades to these are usually backwards-compatible, but check MSRVs.)
# - Documentation
document-features = { version = "0.2", optional = true }

[build-dependencies]
cc = { version = "1", optional = true }

[dev-dependencies]
hex = "0.4"

[lib]
name = "equihash"
bench = false

[[bench]]
name = "solver"
harness = false
required-features = ["solver"]
