//! Prototype 2: Semolina's Montgomery arithmetic as inline `asm!` blocks.
//!
//! Operands live in registers chosen by LLVM (no pointers, no ABI), and
//! `options(pure, nomem, nostack)` lets the optimizer treat each block as a
//! pure function: it can inline the wrappers, keep values in registers
//! between blocks, and CSE or hoist repeated computations.
//!
//! The instruction sequences are register-renamed transcriptions of the
//! verified routines in `proto.S` (themselves byte-identical to Semolina
//! v0.1.4), with the rhs limbs supplied in registers instead of loaded from
//! memory.

use crate::{Limbs, INV, P0, P1};
use core::arch::asm;

/// Montgomery multiplication of canonical Montgomery residues.
#[inline(always)]
pub fn mul(a: &Limbs, b: &Limbs) -> Limbs {
    let (o0, o1, o2, o3): (u64, u64, u64, u64);
    unsafe {
        asm!(
            // Round 0: a * b[0], then cancel the low limb.
            "mul {r0}, {a0}, {b0}",
            "mul {r1}, {a1}, {b0}",
            "mul {r2}, {a2}, {b0}",
            "mul {r3}, {a3}, {b0}",
            "umulh {t0}, {a0}, {b0}",
            "umulh {t1}, {a1}, {b0}",
            "mul {q}, {inv}, {r0}",
            "umulh {t2}, {a2}, {b0}",
            "umulh {t3}, {a3}, {b0}",
            "adds {r1}, {r1}, {t0}",
            "adcs {r2}, {r2}, {t1}",
            "mul {t1}, {p1}, {q}",
            "adcs {r3}, {r3}, {t2}",
            "adc {r4}, xzr, {t3}",
            "lsl {t3}, {q}, #62",
            "subs xzr, {r0}, #1",
            "umulh {t0}, {p0}, {q}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {p1}, {q}",
            "adcs {r2}, {r2}, xzr",
            "adcs {r3}, {r3}, {t3}",
            "lsr {t3}, {q}, #2",
            "adc {r4}, {r4}, xzr",
            "adds {r0}, {r1}, {t0}",
            "mul {t0}, {a0}, {b1}",
            "adcs {r1}, {r2}, {t1}",
            "mul {t1}, {a1}, {b1}",
            "adcs {r2}, {r3}, xzr",
            "mul {t2}, {a2}, {b1}",
            "adcs {r3}, {r4}, {t3}",
            "mul {t3}, {a3}, {b1}",
            "adc {r4}, xzr, xzr",
            // Round 1.
            "adds {r0}, {r0}, {t0}",
            "umulh {t0}, {a0}, {b1}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {a1}, {b1}",
            "adcs {r2}, {r2}, {t2}",
            "mul {q}, {inv}, {r0}",
            "umulh {t2}, {a2}, {b1}",
            "adcs {r3}, {r3}, {t3}",
            "umulh {t3}, {a3}, {b1}",
            "adc {r4}, {r4}, xzr",
            "adds {r1}, {r1}, {t0}",
            "adcs {r2}, {r2}, {t1}",
            "mul {t1}, {p1}, {q}",
            "adcs {r3}, {r3}, {t2}",
            "adc {r4}, {r4}, {t3}",
            "lsl {t3}, {q}, #62",
            "subs xzr, {r0}, #1",
            "umulh {t0}, {p0}, {q}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {p1}, {q}",
            "adcs {r2}, {r2}, xzr",
            "adcs {r3}, {r3}, {t3}",
            "lsr {t3}, {q}, #2",
            "adc {r4}, {r4}, xzr",
            "adds {r0}, {r1}, {t0}",
            "mul {t0}, {a0}, {b2}",
            "adcs {r1}, {r2}, {t1}",
            "mul {t1}, {a1}, {b2}",
            "adcs {r2}, {r3}, xzr",
            "mul {t2}, {a2}, {b2}",
            "adcs {r3}, {r4}, {t3}",
            "mul {t3}, {a3}, {b2}",
            "adc {r4}, xzr, xzr",
            // Round 2.
            "adds {r0}, {r0}, {t0}",
            "umulh {t0}, {a0}, {b2}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {a1}, {b2}",
            "adcs {r2}, {r2}, {t2}",
            "mul {q}, {inv}, {r0}",
            "umulh {t2}, {a2}, {b2}",
            "adcs {r3}, {r3}, {t3}",
            "umulh {t3}, {a3}, {b2}",
            "adc {r4}, {r4}, xzr",
            "adds {r1}, {r1}, {t0}",
            "adcs {r2}, {r2}, {t1}",
            "mul {t1}, {p1}, {q}",
            "adcs {r3}, {r3}, {t2}",
            "adc {r4}, {r4}, {t3}",
            "lsl {t3}, {q}, #62",
            "subs xzr, {r0}, #1",
            "umulh {t0}, {p0}, {q}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {p1}, {q}",
            "adcs {r2}, {r2}, xzr",
            "adcs {r3}, {r3}, {t3}",
            "lsr {t3}, {q}, #2",
            "adc {r4}, {r4}, xzr",
            "adds {r0}, {r1}, {t0}",
            "mul {t0}, {a0}, {b3}",
            "adcs {r1}, {r2}, {t1}",
            "mul {t1}, {a1}, {b3}",
            "adcs {r2}, {r3}, xzr",
            "mul {t2}, {a2}, {b3}",
            "adcs {r3}, {r4}, {t3}",
            "mul {t3}, {a3}, {b3}",
            "adc {r4}, xzr, xzr",
            // Round 3.
            "adds {r0}, {r0}, {t0}",
            "umulh {t0}, {a0}, {b3}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {a1}, {b3}",
            "adcs {r2}, {r2}, {t2}",
            "mul {q}, {inv}, {r0}",
            "umulh {t2}, {a2}, {b3}",
            "adcs {r3}, {r3}, {t3}",
            "umulh {t3}, {a3}, {b3}",
            "adc {r4}, {r4}, xzr",
            "adds {r1}, {r1}, {t0}",
            "adcs {r2}, {r2}, {t1}",
            "mul {t1}, {p1}, {q}",
            "adcs {r3}, {r3}, {t2}",
            "adc {r4}, {r4}, {t3}",
            "lsl {t3}, {q}, #62",
            "subs xzr, {r0}, #1",
            "umulh {t0}, {p0}, {q}",
            "adcs {r1}, {r1}, {t1}",
            "umulh {t1}, {p1}, {q}",
            "adcs {r2}, {r2}, xzr",
            "adcs {r3}, {r3}, {t3}",
            "lsr {t3}, {q}, #2",
            "adc {r4}, {r4}, xzr",
            // Final shift.
            "adds {r0}, {r1}, {t0}",
            "adcs {r1}, {r2}, {t1}",
            "adcs {r2}, {r3}, xzr",
            "adcs {r3}, {r4}, {t3}",
            "adc {r4}, xzr, xzr",
            // Conditional subtraction of p = [p0, p1, 0, 2^62].
            "mov {q}, #0x4000000000000000",
            "subs {t0}, {r0}, {p0}",
            "sbcs {t1}, {r1}, {p1}",
            "sbcs {t2}, {r2}, xzr",
            "sbcs {t3}, {r3}, {q}",
            "sbcs xzr, {r4}, xzr",
            "csel {r0}, {r0}, {t0}, lo",
            "csel {r1}, {r1}, {t1}, lo",
            "csel {r2}, {r2}, {t2}, lo",
            "csel {r3}, {r3}, {t3}, lo",
            a0 = in(reg) a[0],
            a1 = in(reg) a[1],
            a2 = in(reg) a[2],
            a3 = in(reg) a[3],
            b0 = in(reg) b[0],
            b1 = in(reg) b[1],
            b2 = in(reg) b[2],
            b3 = in(reg) b[3],
            p0 = in(reg) P0,
            p1 = in(reg) P1,
            inv = in(reg) INV,
            q = out(reg) _,
            t0 = out(reg) _,
            t1 = out(reg) _,
            t2 = out(reg) _,
            t3 = out(reg) _,
            r0 = out(reg) o0,
            r1 = out(reg) o1,
            r2 = out(reg) o2,
            r3 = out(reg) o3,
            r4 = out(reg) _,
            options(pure, nomem, nostack),
        );
    }
    [o0, o1, o2, o3]
}

/// Montgomery squaring of a canonical Montgomery residue.
#[inline(always)]
pub fn sqr(a: &Limbs) -> Limbs {
    let mut a0 = a[0];
    let mut a1 = a[1];
    let mut a2 = a[2];
    let mut a3 = a[3];
    unsafe {
        asm!(
            // 512-bit square: cross products, doubling, diagonals.
            "mul {z1}, {a1}, {a0}",
            "umulh {w1}, {a1}, {a0}",
            "mul {z2}, {a2}, {a0}",
            "umulh {w2}, {a2}, {a0}",
            "mul {z3}, {a3}, {a0}",
            "umulh {z4}, {a3}, {a0}",
            "adds {z2}, {z2}, {w1}",
            "mul {w0}, {a2}, {a1}",
            "umulh {w1}, {a2}, {a1}",
            "adcs {z3}, {z3}, {w2}",
            "mul {w2}, {a3}, {a1}",
            "umulh {w3}, {a3}, {a1}",
            "adc {z4}, {z4}, xzr",
            "mul {z5}, {a3}, {a2}",
            "umulh {z6}, {a3}, {a2}",
            "adds {w1}, {w1}, {w2}",
            "mul {z0}, {a0}, {a0}",
            "adc {w2}, {w3}, xzr",
            "adds {z3}, {z3}, {w0}",
            "umulh {a0}, {a0}, {a0}",
            "adcs {z4}, {z4}, {w1}",
            "mul {w1}, {a1}, {a1}",
            "adcs {z5}, {z5}, {w2}",
            "umulh {a1}, {a1}, {a1}",
            "adc {z6}, {z6}, xzr",
            "adds {z1}, {z1}, {z1}",
            "mul {w2}, {a2}, {a2}",
            "adcs {z2}, {z2}, {z2}",
            "umulh {a2}, {a2}, {a2}",
            "adcs {z3}, {z3}, {z3}",
            "mul {w3}, {a3}, {a3}",
            "adcs {z4}, {z4}, {z4}",
            "umulh {a3}, {a3}, {a3}",
            "adcs {z5}, {z5}, {z5}",
            "adcs {z6}, {z6}, {z6}",
            "adc {z7}, xzr, xzr",
            "mul {q}, {inv}, {z0}",
            "adds {z1}, {z1}, {a0}",
            "adcs {z2}, {z2}, {w1}",
            "adcs {z3}, {z3}, {a1}",
            "adcs {z4}, {z4}, {w2}",
            "adcs {z5}, {z5}, {a2}",
            "adcs {z6}, {z6}, {w3}",
            "adc {z7}, {z7}, {a3}",
            // Four Montgomery cancellations on the low half.
            "mul {w1}, {p1}, {q}",
            "lsl {w3}, {q}, #62",
            "subs xzr, {z0}, #1",
            "umulh {w0}, {p0}, {q}",
            "adcs {z1}, {z1}, {w1}",
            "umulh {w1}, {p1}, {q}",
            "adcs {z2}, {z2}, xzr",
            "adcs {z3}, {z3}, {w3}",
            "lsr {w3}, {q}, #2",
            "adc {cy}, xzr, xzr",
            "adds {z0}, {z1}, {w0}",
            "adcs {z1}, {z2}, {w1}",
            "adcs {z2}, {z3}, xzr",
            "mul {q}, {inv}, {z0}",
            "adc {z3}, {cy}, {w3}",
            "mul {w1}, {p1}, {q}",
            "lsl {w3}, {q}, #62",
            "subs xzr, {z0}, #1",
            "umulh {w0}, {p0}, {q}",
            "adcs {z1}, {z1}, {w1}",
            "umulh {w1}, {p1}, {q}",
            "adcs {z2}, {z2}, xzr",
            "adcs {z3}, {z3}, {w3}",
            "lsr {w3}, {q}, #2",
            "adc {cy}, xzr, xzr",
            "adds {z0}, {z1}, {w0}",
            "adcs {z1}, {z2}, {w1}",
            "adcs {z2}, {z3}, xzr",
            "mul {q}, {inv}, {z0}",
            "adc {z3}, {cy}, {w3}",
            "mul {w1}, {p1}, {q}",
            "lsl {w3}, {q}, #62",
            "subs xzr, {z0}, #1",
            "umulh {w0}, {p0}, {q}",
            "adcs {z1}, {z1}, {w1}",
            "umulh {w1}, {p1}, {q}",
            "adcs {z2}, {z2}, xzr",
            "adcs {z3}, {z3}, {w3}",
            "lsr {w3}, {q}, #2",
            "adc {cy}, xzr, xzr",
            "adds {z0}, {z1}, {w0}",
            "adcs {z1}, {z2}, {w1}",
            "adcs {z2}, {z3}, xzr",
            "mul {q}, {inv}, {z0}",
            "adc {z3}, {cy}, {w3}",
            "mul {w1}, {p1}, {q}",
            "lsl {w3}, {q}, #62",
            "subs xzr, {z0}, #1",
            "umulh {w0}, {p0}, {q}",
            "adcs {z1}, {z1}, {w1}",
            "umulh {w1}, {p1}, {q}",
            "adcs {z2}, {z2}, xzr",
            "adcs {z3}, {z3}, {w3}",
            "lsr {w3}, {q}, #2",
            "adc {cy}, xzr, xzr",
            "adds {z0}, {z1}, {w0}",
            "adcs {z1}, {z2}, {w1}",
            "adcs {z2}, {z3}, xzr",
            "adc {z3}, {cy}, {w3}",
            // Add the upper half of the square.
            "adds {a0}, {z0}, {z4}",
            "adcs {a1}, {z1}, {z5}",
            "adcs {a2}, {z2}, {z6}",
            "adc {a3}, {z3}, {z7}",
            // Conditional subtraction (candidate < 1.25p).
            "mov {q}, #0x4000000000000000",
            "subs {z0}, {a0}, {p0}",
            "sbcs {z1}, {a1}, {p1}",
            "sbcs {z2}, {a2}, xzr",
            "sbcs {z3}, {a3}, {q}",
            "csel {a0}, {a0}, {z0}, lo",
            "csel {a1}, {a1}, {z1}, lo",
            "csel {a2}, {a2}, {z2}, lo",
            "csel {a3}, {a3}, {z3}, lo",
            a0 = inout(reg) a0,
            a1 = inout(reg) a1,
            a2 = inout(reg) a2,
            a3 = inout(reg) a3,
            p0 = in(reg) P0,
            p1 = in(reg) P1,
            inv = in(reg) INV,
            q = out(reg) _,
            cy = out(reg) _,
            z0 = out(reg) _,
            z1 = out(reg) _,
            z2 = out(reg) _,
            z3 = out(reg) _,
            z4 = out(reg) _,
            z5 = out(reg) _,
            z6 = out(reg) _,
            z7 = out(reg) _,
            w0 = out(reg) _,
            w1 = out(reg) _,
            w2 = out(reg) _,
            w3 = out(reg) _,
            options(pure, nomem, nostack),
        );
    }
    [a0, a1, a2, a3]
}
