[package]
name = "zakura-bellman"
description = "zk-SNARK library"
keywords = ["cryptography", "zero-knowledge", "zksnarks", "groth16", "zcash"]
categories = ["cryptography"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "bellman"

[dependencies]
bitvec = "1"
blake2s_simd = "1"
ff = "0.14"
group = "0.14"
pairing = { workspace = true, optional = true }
rand = { version = "0.10", features = ["sys_rng"], optional = true, default-features = false }
rand_core = "0.10"
rayon = { version = "1.5.1", optional = true }
subtle = "2.2.1"

[dev-dependencies]
bls12_381 = { workspace = true, features = ["default"] }
criterion = "0.4"
hex-literal = "0.3"
rand = "0.10"
rand_xorshift = "0.5"
sha2 = "0.10"

[features]
default = ["groth16", "multicore"]
groth16 = ["pairing"]
multicore = ["rayon", "rand"]

[[test]]
name = "mimc"
required-features = ["groth16"]

[[bench]]
name = "batch"
harness = false

[[bench]]
name = "prepared_batch"
harness = false
required-features = ["groth16"]

[[bench]]
name = "slow"
harness = false

[[bench]]
name = "reusable_verify"
harness = false
