// Derived from zcash/pasta_curves src/glv.rs and
// sage/glv_boundary_scalars.sage at commit
// f76fecb533003e525160e7e6d299b955a9d78cc4.
// Copyright (c) 2020-2021 The Electric Coin Company.
// Licensed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0
// Modified by Zakura for checked, caller-thread signed-Booth MSM expansion.

#ifndef ZAKURA_PASTA_MSM_GLV_HPP
#define ZAKURA_PASTA_MSM_GLV_HPP

#include <cassert>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <memory>
#include <vector>

#if defined(_MSC_VER) && defined(_M_X64)
# include <intrin.h>
#endif

#include <sppark/curve.hpp>
#include <sppark/pasta.hpp>
#include <sppark/pippenger.hpp>

namespace zakura_pasta_msm {

struct mac64_t {
    uint64_t low;
    uint64_t high;
};

static mac64_t mac64(uint64_t accumulator, uint64_t left, uint64_t right,
                     uint64_t carry)
{
#if defined(_MSC_VER) && defined(_M_X64)
    uint64_t low;
    uint64_t high = _umul128(left, right, &low);
#elif defined(__SIZEOF_INT128__)
    unsigned __int128 product =
        static_cast<unsigned __int128>(left) * right;
    uint64_t low = static_cast<uint64_t>(product);
    uint64_t high = static_cast<uint64_t>(product >> 64);
#else
    const uint64_t left_low = static_cast<uint32_t>(left);
    const uint64_t left_high = left >> 32;
    const uint64_t right_low = static_cast<uint32_t>(right);
    const uint64_t right_high = right >> 32;
    const uint64_t product_low = left_low * right_low;
    const uint64_t product_middle =
        (product_low >> 32) +
        static_cast<uint32_t>(left_low * right_high) +
        static_cast<uint32_t>(left_high * right_low);
    uint64_t low = (product_middle << 32) |
                   static_cast<uint32_t>(product_low);
    uint64_t high = left_high * right_high +
                    (left_low * right_high >> 32) +
                    (left_high * right_low >> 32) +
                    (product_middle >> 32);
#endif

    uint64_t sum = low + accumulator;
    high += sum < low;
    low = sum + carry;
    high += low < sum;
    return mac64_t{low, high};
}

static void schoolbook_mul(const uint64_t left[], size_t left_len,
                           const uint64_t right[], size_t right_len,
                           uint64_t product[])
{
    for (size_t i = 0; i < left_len; i++) {
        uint64_t carry = 0;
        for (size_t j = 0; j < right_len; j++) {
            mac64_t limb =
                mac64(product[i + j], left[i], right[j], carry);
            product[i + j] = limb.low;
            carry = limb.high;
        }
        product[i + right_len] = carry;
    }
}

// Computes round((coefficient * scalar) / 2^384), rejecting a result that
// does not fit the two output limbs.
static bool round_mul_shift(const uint64_t coefficient[5],
                            const uint64_t scalar[4], uint64_t output[2])
{
    uint64_t product[9] = {};
    schoolbook_mul(coefficient, 5, scalar, 4, product);

    uint64_t round = product[5] >> 63;
    output[0] = product[6] + round;
    uint64_t carry = output[0] < product[6];
    output[1] = product[7] + carry;
    return product[8] == 0 && output[1] >= product[7];
}

static void mul128(const uint64_t left[2], const uint64_t right[2],
                   uint64_t output[4])
{
    output[0] = output[1] = output[2] = output[3] = 0;
    schoolbook_mul(left, 2, right, 2, output);
}

static void sub256(const uint64_t left[4], const uint64_t right[4],
                   uint64_t output[4])
{
    uint64_t borrow = 0;
    for (size_t i = 0; i < 4; i++) {
        uint64_t difference = left[i] - right[i];
        uint64_t next_borrow = left[i] < right[i];
        output[i] = difference - borrow;
        next_borrow |= difference < borrow;
        borrow = next_borrow;
    }
}

static uint64_t load64_le(const unsigned char bytes[8])
{
    uint64_t output = 0;
    for (size_t i = 0; i < 8; i++)
        output |= static_cast<uint64_t>(bytes[i]) << (8 * i);
    return output;
}

static void store64_le(unsigned char bytes[8], uint64_t value)
{
    for (size_t i = 0; i < 8; i++) {
        bytes[i] = static_cast<unsigned char>(value);
        value >>= 8;
    }
}

struct glv_params_t {
    uint64_t v1a[2];
    uint64_t v1b_negative[2];
    uint64_t v2a[2];
    uint64_t v2b[2];
    uint64_t g1[5];
    uint64_t g2[5];
};

// Generated by zcash/pasta_curves sage/glv_constants.sage and independently
// checked in that crate's src/glv.rs test suite.
static const glv_params_t PALLAS_GLV = {
    {0x7fcae1c700000001, 0x49e69d1640f04915},
    {0x8cb1279300000000, 0x49e69d1640a89953},
    {0x8cb1279300000000, 0x49e69d1640a89953},
    {0x0c7c095a00000001, 0x93cd3a2c8198e269},
    {
        0x111f686111afc293,
        0xc35fbd4d086862e0,
        0x31f0256800000002,
        0x4f34e8b2066389a4,
        0x2,
    },
    {
        0x4a95a2d972171db4,
        0x61afdea68480fa55,
        0x32c49e4bffffffff,
        0x279a745902a2654e,
        0x1,
    },
};

static const glv_params_t VESTA_GLV = {
    {0x7fcae1c700000000, 0x49e69d1640f04915},
    {0x8cb1279300000001, 0x49e69d1640a89953},
    {0x8cb1279300000001, 0x49e69d1640a89953},
    {0x0c7c095a00000001, 0x93cd3a2c8198e269},
    {
        0x841d8d62296e1563,
        0xc35fbd4d0afe9926,
        0x31f0256800000002,
        0x4f34e8b2066389a4,
        0x2,
    },
    {
        0x841414c24bf99a83,
        0x61afdea685cc1578,
        0x32c49e4c00000003,
        0x279a745902a2654e,
        0x1,
    },
};

struct glv_half_t {
    bool negative;
    uint64_t magnitude[2];
};

static bool signed_half(const uint64_t value[4], glv_half_t& output)
{
    uint64_t extension = value[1] >> 63 ? UINT64_MAX : 0;
    if (value[2] != extension || value[3] != extension)
        return false;

    output.negative = value[3] >> 63;
    if (output.negative) {
        output.magnitude[0] = ~value[0] + 1;
        output.magnitude[1] =
            ~value[1] + (output.magnitude[0] == 0);
    } else {
        output.magnitude[0] = value[0];
        output.magnitude[1] = value[1];
    }
    return (output.magnitude[1] >> 63) == 0;
}

struct glv_split_t {
    glv_half_t first;
    glv_half_t second;
};

static const size_t PASTA_SCALAR_BYTES = 32;
static const size_t GLV_BITS = 127;
static const size_t GLV_BYTES = (GLV_BITS + 7) / 8;

static bool glv_decompose(const unsigned char scalar[PASTA_SCALAR_BYTES],
                          const glv_params_t& params, glv_split_t& output)
{
    uint64_t scalar_limbs[4];
    for (size_t i = 0; i < 4; i++)
        scalar_limbs[i] = load64_le(&scalar[8 * i]);

    uint64_t c1[2], c2[2];
    if (!round_mul_shift(params.g1, scalar_limbs, c1) ||
        !round_mul_shift(params.g2, scalar_limbs, c2)) {
        return false;
    }

    uint64_t c1v1a[4], c2v2a[4], c1v1b[4], c2v2b[4];
    mul128(c1, params.v1a, c1v1a);
    mul128(c2, params.v2a, c2v2a);
    mul128(c1, params.v1b_negative, c1v1b);
    mul128(c2, params.v2b, c2v2b);

    uint64_t intermediate[4], first[4], second[4];
    sub256(scalar_limbs, c1v1a, intermediate);
    sub256(intermediate, c2v2a, first);
    sub256(c1v1b, c2v2b, second);
    return signed_half(first, output.first) &&
           signed_half(second, output.second);
}

static void store_half(unsigned char output[GLV_BYTES],
                       const glv_half_t& half)
{
    store64_le(&output[0], half.magnitude[0]);
    store64_le(&output[8], half.magnitude[1]);
}

template<class affine_t, class field_t>
static affine_t pasta_endomorphism(const affine_t& point,
                                   const field_t& zeta)
{
    affine_t output = point;
    output.X *= zeta;
    return output;
}

template<class point_t, class scalar_t, class field_t,
         class affine_t = typename point_t::affine_type>
static void mult_pippenger_glv_signed_serial(
    point_t& output, const affine_t points[], size_t npoints,
    const scalar_t montgomery_scalars[], const glv_params_t& params,
    const field_t& zeta)
{
    using canonical_scalar = typename scalar_t::pow_t;
    static_assert(sizeof(scalar_t) == PASTA_SCALAR_BYTES,
                  "Pasta scalars must contain exactly 32 bytes");

    if (npoints == 0) {
        output.inf();
        return;
    }

    if (npoints > std::numeric_limits<size_t>::max() /
                      (2 * GLV_BYTES)) {
        mult_pippenger_signed_serial(
            output, points, npoints, montgomery_scalars);
        return;
    }

    // Canonicalize all scalars in one pass before expanding the point set.
    std::unique_ptr<canonical_scalar[]> canonical_scalars(
        new canonical_scalar[npoints]);
    for (size_t i = 0; i < npoints; i++)
        montgomery_scalars[i].to_scalar(canonical_scalars[i]);

    const size_t expanded_npoints = 2 * npoints;
    std::vector<affine_t> expanded_points(expanded_npoints);
    std::vector<unsigned char> expanded_scalars(
        expanded_npoints * GLV_BYTES);
    for (size_t i = 0; i < npoints; i++) {
        glv_split_t split;
        bool valid = glv_decompose(canonical_scalars[i], params, split);
        assert(valid && "Pasta GLV decomposition must fit signed halves");
        if (!valid) {
            // Keep release builds correct if the constants or arithmetic are
            // ever changed without preserving the checked GLV bounds.
            mult_pippenger_signed_serial(
                output, points, npoints, montgomery_scalars);
            return;
        }

        expanded_points[2 * i] = points[i];
        expanded_points[2 * i].cneg(split.first.negative);
        store_half(&expanded_scalars[2 * i * GLV_BYTES], split.first);

        expanded_points[2 * i + 1] =
            pasta_endomorphism(points[i], zeta);
        expanded_points[2 * i + 1].cneg(split.second.negative);
        store_half(
            &expanded_scalars[(2 * i + 1) * GLV_BYTES], split.second);
    }

    mult_pippenger_signed_serial_raw(
        output, expanded_points.data(), expanded_npoints,
        expanded_scalars.data(), GLV_BITS);

#ifndef NDEBUG
    point_t expected;
    mult_pippenger_signed_serial(
        expected, points, npoints, montgomery_scalars);
    affine_t actual_affine = output.to_affine();
    affine_t expected_affine = expected.to_affine();
    assert(actual_affine.X == expected_affine.X &&
           actual_affine.Y == expected_affine.Y);
#endif
}

static pallas_t pallas_zeta()
{
    static const vec256 limbs = {
        0x02021cf6619a153d,
        0x9e8c26974980b78e,
        0x2a676d5cc87a4666,
        0x15d8049da7a17876,
    };
    return pallas_t(limbs);
}

static vesta_t vesta_zeta()
{
    static const vec256 limbs = {
        0x7c541a8480111122,
        0x40630b9c56ed29da,
        0x02c275fb135b2b29,
        0x121d29f888245b10,
    };
    return vesta_t(limbs);
}

} // namespace zakura_pasta_msm

#endif
