[package]
name = "zakura-equihash"
description = "The Equihash Proof-of-Work function"
version = "0.3.0"
publish = false
authors = ["Jack Grigg <jack@z.cash>"]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
std = ["document-features"]

## Experimental tromp solver support, builds the C++ tromp solver and Rust FFI layer.
solver = ["dep:cc", "std"]

[dependencies]
corez = { version = "0.1.1", default-features = false, features = ["alloc"] }
blake2b_simd = { version = "1", default-features = false }

# Dependencies used internally:
# (Breaking upgrades to these are usually backwards-compatible, but check MSRVs.)
# - Documentation
document-features = { version = "0.2", optional = true }

[build-dependencies]
cc = { version = "1", optional = true }

[dev-dependencies]
hex = "0.4"

[lib]
bench = false
