[package]
name = "zakura-reddsa"
description = "A standalone implementation of the RedDSA signature scheme"
keywords = ["cryptography", "signatures", "reddsa", "zcash"]
categories = ["cryptography", "no-std"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "reddsa"

[dependencies]
blake2b_simd = { version = "1", default-features = false }
frost-rerandomized = { version = "3.0.0", features = ["serialization"], optional = true, default-features = false }
group = { version = "0.14", default-features = false }
hex = { version = "0.4", features = ["alloc"], optional = true, default-features = false }
jubjub = { workspace = true }
pasta_curves = { workspace = true }
rand_core = { version = "0.10", default-features = false }
rand_core_06 = { version = "0.6", features = ["getrandom"], optional = true, default-features = false, package = "rand_core" }
serde = { version = "1", features = ["derive"], optional = true }
thiserror = { version = "2.0", optional = true }
zeroize = { version = "1", features = ["zeroize_derive"], optional = true }

[dev-dependencies]
bincode = "1"
criterion = "0.6"
frost-rerandomized = { version = "3.0.0", features = ["test-impl"] }
hex = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
pasta_curves = { workspace = true, features = ["alloc"] }
proptest = "1.6"
proptest-derive = "0.5"
rand = "0.10"
rand_chacha = "0.10"
serde_json = "1.0"

[features]
alloc = ["hex", "jubjub/alloc"]
default = ["std"]
frost = ["frost-rerandomized", "rand_core_06", "alloc"]
nightly = []
serde = ["dep:serde", "frost-rerandomized?/serde"]
std = [
    "blake2b_simd/std",
    "thiserror",
    "zeroize",
    "alloc",
    "serde",
]

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "frost"
harness = false
