[package]
name = "zakura-sapling-crypto"
description = "Cryptographic library for Zcash Sapling"
keywords = ["cryptography", "sapling", "zero-knowledge", "zcash"]
categories = ["cryptography::cryptocurrencies"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "sapling_crypto"

[dependencies]
aes = "0.8"
bellman = { workspace = true, features = ["groth16"], optional = true }
bitvec = { version = "1", default-features = false }
blake2b_simd = { version = "1", default-features = false }
blake2s_simd = { version = "1", default-features = false }
bls12_381 = { workspace = true, features = ["alloc"] }
corez = { version = "0.1.1", features = ["alloc"], default-features = false }
ff = { version = "0.14", default-features = false }
fpe = { version = "0.6", features = ["alloc"], default-features = false }
getset = "0.1"
group = "0.14"
hex = { version = "0.4", features = ["alloc"], default-features = false }
incrementalmerkletree = { version = "0.8.1", features = ["legacy-api"], default-features = false }
jubjub = { workspace = true, features = ["alloc"] }
memuse = { version = "0.2.2", default-features = false }
once_cell = { version = "1", features = ["race", "alloc"], default-features = false }
proptest = { version = ">=1.0.0, <1.7.0", optional = true }
rand = { version = "0.10", default-features = false }
rand_core = { version = "0.10", default-features = false }
rand_core_06 = { version = "0.6", default-features = false, package = "rand_core" }
redjubjub = { workspace = true }
subtle = { version = "2.6", default-features = false }
tracing = { version = "0.1", default-features = false }
zcash_note_encryption = { version = "0.4", features = ["pre-zip-212"] }
zcash_spec = "0.2"
zip32 = { version = "0.2", default-features = false }

[dev-dependencies]
chacha20poly1305 = "0.10"
criterion = "0.5"
incrementalmerkletree = { version = "0.8.1", features = ["legacy-api", "test-dependencies"] }
proptest = ">=1.0.0, <1.7.0"
rand = { version = "0.10", features = ["thread_rng"], default-features = false }
rand_xorshift = "0.5"

[target."cfg(unix)".dev-dependencies]
pprof = { version = "0.15", features = ["criterion", "flamegraph"] }

[features]
circuit = [
    "dep:bellman",
    "bls12_381/bits",
    "bls12_381/groups",
    "bls12_381/pairings",
    "jubjub/bits",
    "std",
]
default = ["multicore", "circuit"]
multicore = ["bellman?/multicore"]
std = [
    "corez/std",
    "group/wnaf-memuse",
    "redjubjub/std",
]
temporary-zcashd = []
test-dependencies = [
    "incrementalmerkletree/test-dependencies",
    "dep:proptest",
    "rand/std_rng",
]

[[bench]]
name = "circuit"
harness = false

[[bench]]
name = "pedersen_hash"
harness = false
