[package]
name = "zakura-bls12-381"
description = "Implementation of the BLS12-381 pairing-friendly elliptic curve construction"
keywords = ["cryptography", "pairing", "bls12-381", "elliptic-curve", "zcash"]
categories = ["cryptography"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[lib]
name = "bls12_381"

[dependencies]
digest = { version = "0.10", optional = true }
ff = { version = "0.14", default-features = false }
group = { version = "0.14", optional = true, default-features = false }
pairing = { workspace = true, optional = true }
rand_core = { version = "0.10", default-features = false }
subtle = { version = "2.2.1", default-features = false }
zeroize = { version = "1.4", optional = true, default-features = false }

[dev-dependencies]
criterion = "0.3"
hex = "0.4"
hex-literal = "0.3"
rand_xorshift = "0.5"
sha2 = "0.10"
sha3 = "0.10"

[features]
alloc = ["group/alloc"]
bits = ["ff/bits"]
default = ["groups", "pairings", "alloc", "bits"]
experimental = ["digest", "groups"]
groups = ["group"]
nightly = ["subtle/nightly"]
pairings = ["groups", "pairing"]
std = ["alloc"]

[[test]]
name = "expand_msg"
required-features = ["alloc", "experimental"]

[[test]]
name = "hash_to_curve_g1"
required-features = ["experimental"]

[[test]]
name = "hash_to_curve_g2"
required-features = ["experimental"]

[[bench]]
name = "groups"
harness = false
required-features = ["groups"]

[[bench]]
name = "hash_to_curve"
harness = false
required-features = ["experimental"]
